# 数据处理

In [5]:
import torch
x = torch.arange(16).reshape(4, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

## 访问元素
1. 获取一个元素

In [11]:
# 访问元素
print(x[1, 2])  # 一个

tensor(6)


2. 获取一列元素

In [12]:
print(x[:, 1])  # 一列

tensor([ 1,  5,  9, 13])


3. 获取一行元素

In [13]:
print(x[1, :])  # 一行

tensor([4, 5, 6, 7])


4. 获取一个子区域
   - 连续的子区域

In [14]:
print(x[1:3, 1:])  # 子区域

tensor([[ 5,  6,  7],
        [ 9, 10, 11]])


   - 跳转的子区域

In [15]:
print(x[::3, ::2])  # 带跳转的子区域

tensor([[ 0,  2],
        [12, 14]])


## 形状
1. 获取形状

In [16]:
print(x.shape)

torch.Size([4, 4])


2. 改变形状

In [17]:
x2 = x.reshape(2, 8)
print(x2.shape)

torch.Size([2, 8])


## 运算
1. 标准运算（+ - * / **）拓展为按元素运算

In [18]:
a = torch.tensor([1, 2, 3, 4], dtype=torch.float64)
b = torch.tensor([-2, -3, -4, -5], dtype=torch.float64)
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

tensor([-1., -1., -1., -1.], dtype=torch.float64)
tensor([3., 5., 7., 9.], dtype=torch.float64)
tensor([ -2.,  -6., -12., -20.], dtype=torch.float64)
tensor([-0.5000, -0.6667, -0.7500, -0.8000], dtype=torch.float64)
tensor([ 1.,  4.,  9., 16.], dtype=torch.float64)


2. 所有元素求和

In [19]:
print(x.sum())

tensor(120)


## 广播机制
## 执行原地操作

In [20]:
z = torch.zeros_like(x)
print('id(z): ',id(z))
z[:] = z + x
print('id(z): ', id(z))

id(z):  2048216765776
id(z):  2048216765776
