# 线性代数

In [3]:
import torch
x = torch.arange(16).reshape(4, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

矩阵的转置

In [4]:
x.T

tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])

所有元素求和

In [5]:
x.sum()

tensor(120)

按指定维度作为轴求和

In [11]:
A = torch.arange(2 * 20).reshape(2, 5, 4)
A


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [12]:
A.shape

torch.Size([2, 5, 4])

In [9]:
A.sum(axis=0)

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

计算总和时保持轴数不变

In [13]:
sum_x = x.sum(axis=1, keepdim=True)
sum_x

tensor([[ 6],
        [22],
        [38],
        [54]])

In [14]:
x / sum_x

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778]])

In [15]:
A.cumsum(axis=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]])

点积(两个向量才能乘)

In [20]:
A[0][0], A[0][1], torch.dot(A[0][0], A[0][1])

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor(38))

等价于

In [21]:
torch.sum(A[0][0] * A[0][1])

tensor(38)

矩阵乘法

In [24]:
A[0], A[0].T, torch.mm(A[0], A[1].T)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]),
 tensor([[ 134,  158,  182,  206,  230],
         [ 478,  566,  654,  742,  830],
         [ 822,  974, 1126, 1278, 1430],
         [1166, 1382, 1598, 1814, 2030],
         [1510, 1790, 2070, 2350, 2630]]))

## 范数
### $L_1$ 范数
向量元素绝对值的求和：
$$\Vert x \Vert_1 = \sum^{n}_{i=1}{x_i}$$

In [26]:
u = torch.tensor([3.0, -4.0])
torch.abs(u).sum()

tensor(7.)

### $L_2$ 范数
向量元素平方和的平方根：
$$\Vert x \Vert_2 = \sqrt{\sum^{n}_{i=1}{x_i^2}}$$

In [27]:
torch.norm(u)

tensor(5.)

### $F$ 范数
矩阵元素平方和的平方根：
$$\Vert x \Vert_F = \sqrt{\sum^{m}_{i=1}\sum^{n}_{j=1}{x_{ij}^2}}$$

In [31]:
torch.norm(torch.ones(4, 9))

tensor(6.)