# 自动求导
## 向量求导
||$x (1,)$|$\boldsymbol x (n,1)$|$\boldsymbol X (n,k)$|
|:-:|:-:|:-:|:-:|
|$y (1,)$|$\frac{\partial y}{\partial x} (1,)$|$\frac{\partial y}{\partial \boldsymbol x} (1,n)$|$\frac{\partial y}{\partial \boldsymbol X} (k,n)$|
|$\boldsymbol y (m,1)$|$\frac{\partial \boldsymbol y}{\partial x} (m,1)$|$\frac{\partial \boldsymbol y}{\partial \boldsymbol x} (m,n)$|$\frac{\partial \boldsymbol y}{\partial \boldsymbol X} (m,k,n)$|
|$\boldsymbol Y (m,l)$|$\frac{\partial \boldsymbol Y}{\partial x} (m,l)$|$\frac{\partial \boldsymbol Y}{\partial \boldsymbol x} (m,l,n)$|$\frac{\partial \boldsymbol Y}{\partial \boldsymbol X} (m,l,k,n)$|

样例：

|$y$|$a$|$\Vert x \Vert^2$|$\left\langle \boldsymbol u, \boldsymbol v \right\rangle$|
|:-:|:-:|:-:|:-:|
|$\frac{\partial y}{\partial \boldsymbol x}$|${\boldsymbol 0}^T$|$2 {\boldsymbol x}^T$|${\boldsymbol u}^T\frac{\partial \boldsymbol v}{\partial \boldsymbol x}+{\boldsymbol v}^T\frac{\partial \boldsymbol u}{\partial \boldsymbol x}$|

- 当 $y$ 为标量而 $\boldsymbol x$ 为向量时，所得导数为转置的向量
- 当 $\boldsymbol y$ 为向量而 $x$ 为标量时，所得导数为同形状的向量

## 数值求导

In [3]:
import torch

x = torch.arange(4.0)
x.requires_grad_(True)
x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), None)

计算函数 $y = 2\boldsymbol x \boldsymbol x^T$

In [5]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [8]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

将某些计算移动到计算图之外，设置为常数

In [10]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
# 此时，u 对于表达式 z 来说就是一个常数
z.sum().backward()
x.grad, x.grad == u

(tensor([0., 1., 4., 9.]), tensor([True, True, True, True]))